# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.refresh_api import RefreshApi


class TestRefreshApi(unittest.TestCase):
    """RefreshApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RefreshApi()

    def tearDown(self) -> None:
        pass

    def test_refresh(self) -> None:
        """Test case for refresh

        Refresh connection data
        """
        pass


if __name__ == '__main__':
    unittest.main()
