# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.update_embedding_provider_request import UpdateEmbeddingProviderRequest

class TestUpdateEmbeddingProviderRequest(unittest.TestCase):
    """UpdateEmbeddingProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateEmbeddingProviderRequest:
        """Test UpdateEmbeddingProviderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateEmbeddingProviderRequest`
        """
        model = UpdateEmbeddingProviderRequest()
        if include_optional:
            return UpdateEmbeddingProviderRequest(
                api_key = '',
                config = None,
                name = '',
                secret_name = ''
            )
        else:
            return UpdateEmbeddingProviderRequest(
        )
        """

    def testUpdateEmbeddingProviderRequest(self):
        """Test UpdateEmbeddingProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
