# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.saved_query_version_info import SavedQueryVersionInfo

class TestSavedQueryVersionInfo(unittest.TestCase):
    """SavedQueryVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavedQueryVersionInfo:
        """Test SavedQueryVersionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SavedQueryVersionInfo`
        """
        model = SavedQueryVersionInfo()
        if include_optional:
            return SavedQueryVersionInfo(
                category = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                has_aggregation = None,
                has_group_by = None,
                has_join = None,
                has_limit = None,
                has_order_by = None,
                has_predicate = None,
                num_tables = None,
                sql = '',
                sql_hash = '',
                table_size = None,
                version = 56
            )
        else:
            return SavedQueryVersionInfo(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sql = '',
                sql_hash = '',
                version = 56,
        )
        """

    def testSavedQueryVersionInfo(self):
        """Test SavedQueryVersionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
