# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.list_indexes_response import ListIndexesResponse

class TestListIndexesResponse(unittest.TestCase):
    """ListIndexesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListIndexesResponse:
        """Test ListIndexesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListIndexesResponse`
        """
        model = ListIndexesResponse()
        if include_optional:
            return ListIndexesResponse(
                indexes = [
                    hotdata.models.index_info_response.IndexInfoResponse(
                        columns = [
                            ''
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        index_name = '', 
                        index_type = '', 
                        metric = '', 
                        status = 'ready', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListIndexesResponse(
                indexes = [
                    hotdata.models.index_info_response.IndexInfoResponse(
                        columns = [
                            ''
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        index_name = '', 
                        index_type = '', 
                        metric = '', 
                        status = 'ready', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListIndexesResponse(self):
        """Test ListIndexesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
