# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.upsert_workspace_context_response import UpsertWorkspaceContextResponse

class TestUpsertWorkspaceContextResponse(unittest.TestCase):
    """UpsertWorkspaceContextResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertWorkspaceContextResponse:
        """Test UpsertWorkspaceContextResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertWorkspaceContextResponse`
        """
        model = UpsertWorkspaceContextResponse()
        if include_optional:
            return UpsertWorkspaceContextResponse(
                context = hotdata.models.workspace_context_entry.WorkspaceContextEntry(
                    content = '', 
                    name = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return UpsertWorkspaceContextResponse(
                context = hotdata.models.workspace_context_entry.WorkspaceContextEntry(
                    content = '', 
                    name = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testUpsertWorkspaceContextResponse(self):
        """Test UpsertWorkspaceContextResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
