# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for instant databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.database_lineage_response import DatabaseLineageResponse

class TestDatabaseLineageResponse(unittest.TestCase):
    """DatabaseLineageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseLineageResponse:
        """Test DatabaseLineageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseLineageResponse`
        """
        model = DatabaseLineageResponse()
        if include_optional:
            return DatabaseLineageResponse(
                ancestors = [
                    hotdata.models.lineage_ancestor_info.LineageAncestorInfo(
                        database_id = '', 
                        description = '', 
                        exists = True, 
                        forked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        snapshot_id = 56, )
                    ],
                ancestors_truncated = True,
                database_id = '',
                fork_count = 56,
                forks = [
                    hotdata.models.lineage_fork_info.LineageForkInfo(
                        database_id = '', 
                        description = '', 
                        exists = True, 
                        forked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        snapshot_id = 56, )
                    ],
                root_id = ''
            )
        else:
            return DatabaseLineageResponse(
                ancestors = [
                    hotdata.models.lineage_ancestor_info.LineageAncestorInfo(
                        database_id = '', 
                        description = '', 
                        exists = True, 
                        forked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        snapshot_id = 56, )
                    ],
                ancestors_truncated = True,
                database_id = '',
                fork_count = 56,
                forks = [
                    hotdata.models.lineage_fork_info.LineageForkInfo(
                        database_id = '', 
                        description = '', 
                        exists = True, 
                        forked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        snapshot_id = 56, )
                    ],
                root_id = '',
        )
        """

    def testDatabaseLineageResponse(self):
        """Test DatabaseLineageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
