# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.indexes_api import IndexesApi


class TestIndexesApi(unittest.TestCase):
    """IndexesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IndexesApi()

    def tearDown(self) -> None:
        pass

    def test_create_index(self) -> None:
        """Test case for create_index

        Create an index on a table
        """
        pass

    def test_delete_index(self) -> None:
        """Test case for delete_index

        Delete an index
        """
        pass

    def test_list_indexes(self) -> None:
        """Test case for list_indexes

        List indexes on a table
        """
        pass


if __name__ == '__main__':
    unittest.main()
