# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.list_workspaces_response import ListWorkspacesResponse

class TestListWorkspacesResponse(unittest.TestCase):
    """ListWorkspacesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkspacesResponse:
        """Test ListWorkspacesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkspacesResponse`
        """
        model = ListWorkspacesResponse()
        if include_optional:
            return ListWorkspacesResponse(
                ok = True,
                workspaces = [
                    hotdata.models.workspace_list_item.WorkspaceListItem(
                        public_id = 'ws_abc123', 
                        name = 'production-analytics', 
                        active = True, 
                        favorite = True, 
                        provision_status = 'provisioned', 
                        namespace = 'workspace-ws_abc123', )
                    ]
            )
        else:
            return ListWorkspacesResponse(
                ok = True,
                workspaces = [
                    hotdata.models.workspace_list_item.WorkspaceListItem(
                        public_id = 'ws_abc123', 
                        name = 'production-analytics', 
                        active = True, 
                        favorite = True, 
                        provision_status = 'provisioned', 
                        namespace = 'workspace-ws_abc123', )
                    ],
        )
        """

    def testListWorkspacesResponse(self):
        """Test ListWorkspacesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
