# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.column_type_spec import ColumnTypeSpec

class TestColumnTypeSpec(unittest.TestCase):
    """ColumnTypeSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ColumnTypeSpec:
        """Test ColumnTypeSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ColumnTypeSpec`
        """
        model = ColumnTypeSpec()
        if include_optional:
            return ColumnTypeSpec(
                geometry_type = None,
                precision = None,
                scale = None,
                srid = None,
                type = ''
            )
        else:
            return ColumnTypeSpec(
                type = '',
        )
        """

    def testColumnTypeSpec(self):
        """Test ColumnTypeSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
