# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.query_response import QueryResponse

class TestQueryResponse(unittest.TestCase):
    """QueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryResponse:
        """Test QueryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryResponse`
        """
        model = QueryResponse()
        if include_optional:
            return QueryResponse(
                columns = [
                    ''
                    ],
                execution_time_ms = 0,
                nullable = [
                    True
                    ],
                preview_row_count = 56,
                query_run_id = '',
                result_id = '',
                row_count = 0,
                rows = [
                    [
                        null
                        ]
                    ],
                total_row_count = 56,
                truncated = True,
                warning = ''
            )
        else:
            return QueryResponse(
                columns = [
                    ''
                    ],
                execution_time_ms = 0,
                nullable = [
                    True
                    ],
                preview_row_count = 56,
                query_run_id = '',
                row_count = 0,
                rows = [
                    [
                        null
                        ]
                    ],
                truncated = True,
        )
        """

    def testQueryResponse(self):
        """Test QueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
