# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.finalize_upload_response import FinalizeUploadResponse

class TestFinalizeUploadResponse(unittest.TestCase):
    """FinalizeUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinalizeUploadResponse:
        """Test FinalizeUploadResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinalizeUploadResponse`
        """
        model = FinalizeUploadResponse()
        if include_optional:
            return FinalizeUploadResponse(
                content_type = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size_bytes = 56,
                status = '',
                upload_id = ''
            )
        else:
            return FinalizeUploadResponse(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size_bytes = 56,
                status = '',
                upload_id = '',
        )
        """

    def testFinalizeUploadResponse(self):
        """Test FinalizeUploadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
