# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.list_query_runs_response import ListQueryRunsResponse

class TestListQueryRunsResponse(unittest.TestCase):
    """ListQueryRunsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListQueryRunsResponse:
        """Test ListQueryRunsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListQueryRunsResponse`
        """
        model = ListQueryRunsResponse()
        if include_optional:
            return ListQueryRunsResponse(
                count = 0,
                has_more = True,
                limit = 0,
                next_cursor = None,
                query_runs = [
                    hotdata.models.query_run_info.QueryRunInfo(
                        completed_at = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error_message = null, 
                        execution_time_ms = null, 
                        id = '', 
                        result_id = null, 
                        row_count = null, 
                        saved_query_id = null, 
                        saved_query_version = null, 
                        snapshot_id = '', 
                        sql_hash = '', 
                        sql_text = '', 
                        status = '', 
                        trace_id = null, 
                        warning_message = null, )
                    ]
            )
        else:
            return ListQueryRunsResponse(
                count = 0,
                has_more = True,
                limit = 0,
                query_runs = [
                    hotdata.models.query_run_info.QueryRunInfo(
                        completed_at = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error_message = null, 
                        execution_time_ms = null, 
                        id = '', 
                        result_id = null, 
                        row_count = null, 
                        saved_query_id = null, 
                        saved_query_version = null, 
                        snapshot_id = '', 
                        sql_hash = '', 
                        sql_text = '', 
                        status = '', 
                        trace_id = null, 
                        warning_message = null, )
                    ],
        )
        """

    def testListQueryRunsResponse(self):
        """Test ListQueryRunsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
