# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.table_info import TableInfo

class TestTableInfo(unittest.TestCase):
    """TableInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableInfo:
        """Test TableInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableInfo`
        """
        model = TableInfo()
        if include_optional:
            return TableInfo(
                columns = [
                    hotdata.models.column_info.ColumnInfo(
                        data_type = '', 
                        name = '', 
                        nullable = True, )
                    ],
                connection = '',
                last_sync = None,
                var_schema = '',
                synced = True,
                table = ''
            )
        else:
            return TableInfo(
                connection = '',
                var_schema = '',
                synced = True,
                table = '',
        )
        """

    def testTableInfo(self):
        """Test TableInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
