# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.list_databases_response import ListDatabasesResponse

class TestListDatabasesResponse(unittest.TestCase):
    """ListDatabasesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListDatabasesResponse:
        """Test ListDatabasesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListDatabasesResponse`
        """
        model = ListDatabasesResponse()
        if include_optional:
            return ListDatabasesResponse(
                databases = [
                    hotdata.models.database_summary.DatabaseSummary(
                        description = '', 
                        id = '', )
                    ]
            )
        else:
            return ListDatabasesResponse(
                databases = [
                    hotdata.models.database_summary.DatabaseSummary(
                        description = '', 
                        id = '', )
                    ],
        )
        """

    def testListDatabasesResponse(self):
        """Test ListDatabasesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
