# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.workspace_context_api import WorkspaceContextApi


class TestWorkspaceContextApi(unittest.TestCase):
    """WorkspaceContextApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceContextApi()

    def tearDown(self) -> None:
        pass

    def test_get_workspace_context(self) -> None:
        """Test case for get_workspace_context

        Get one workspace context
        """
        pass

    def test_list_workspace_contexts(self) -> None:
        """Test case for list_workspace_contexts

        List workspace contexts
        """
        pass

    def test_upsert_workspace_context(self) -> None:
        """Test case for upsert_workspace_context

        Create or update workspace context
        """
        pass


if __name__ == '__main__':
    unittest.main()
