# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.list_connection_types_response import ListConnectionTypesResponse

class TestListConnectionTypesResponse(unittest.TestCase):
    """ListConnectionTypesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListConnectionTypesResponse:
        """Test ListConnectionTypesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListConnectionTypesResponse`
        """
        model = ListConnectionTypesResponse()
        if include_optional:
            return ListConnectionTypesResponse(
                connection_types = [
                    hotdata.models.connection_type_summary.ConnectionTypeSummary(
                        label = '', 
                        name = '', )
                    ]
            )
        else:
            return ListConnectionTypesResponse(
                connection_types = [
                    hotdata.models.connection_type_summary.ConnectionTypeSummary(
                        label = '', 
                        name = '', )
                    ],
        )
        """

    def testListConnectionTypesResponse(self):
        """Test ListConnectionTypesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
