# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.submit_job_response import SubmitJobResponse

class TestSubmitJobResponse(unittest.TestCase):
    """SubmitJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitJobResponse:
        """Test SubmitJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitJobResponse`
        """
        model = SubmitJobResponse()
        if include_optional:
            return SubmitJobResponse(
                id = '',
                status = 'pending',
                status_url = ''
            )
        else:
            return SubmitJobResponse(
                id = '',
                status = 'pending',
                status_url = '',
        )
        """

    def testSubmitJobResponse(self):
        """Test SubmitJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
