# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.column_profile_detail_one_of4 import ColumnProfileDetailOneOf4

class TestColumnProfileDetailOneOf4(unittest.TestCase):
    """ColumnProfileDetailOneOf4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ColumnProfileDetailOneOf4:
        """Test ColumnProfileDetailOneOf4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ColumnProfileDetailOneOf4`
        """
        model = ColumnProfileDetailOneOf4()
        if include_optional:
            return ColumnProfileDetailOneOf4(
                false_count = 0,
                true_count = 0,
                type = 'boolean'
            )
        else:
            return ColumnProfileDetailOneOf4(
                false_count = 0,
                true_count = 0,
                type = 'boolean',
        )
        """

    def testColumnProfileDetailOneOf4(self):
        """Test ColumnProfileDetailOneOf4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
