# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.batch_create_upload_request import BatchCreateUploadRequest

class TestBatchCreateUploadRequest(unittest.TestCase):
    """BatchCreateUploadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchCreateUploadRequest:
        """Test BatchCreateUploadRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchCreateUploadRequest`
        """
        model = BatchCreateUploadRequest()
        if include_optional:
            return BatchCreateUploadRequest(
                uploads = [
                    hotdata.models.create_upload_request.CreateUploadRequest(
                        checksum_algo = '', 
                        checksum_value = '', 
                        content_encoding = '', 
                        content_type = '', 
                        declared_size_bytes = 0, 
                        filename = '', 
                        part_size = 0, )
                    ]
            )
        else:
            return BatchCreateUploadRequest(
                uploads = [
                    hotdata.models.create_upload_request.CreateUploadRequest(
                        checksum_algo = '', 
                        checksum_value = '', 
                        content_encoding = '', 
                        content_type = '', 
                        declared_size_bytes = 0, 
                        filename = '', 
                        part_size = 0, )
                    ],
        )
        """

    def testBatchCreateUploadRequest(self):
        """Test BatchCreateUploadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
