# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.managed_table_response import ManagedTableResponse

class TestManagedTableResponse(unittest.TestCase):
    """ManagedTableResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedTableResponse:
        """Test ManagedTableResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedTableResponse`
        """
        model = ManagedTableResponse()
        if include_optional:
            return ManagedTableResponse(
                connection_id = '',
                var_schema = '',
                table = ''
            )
        else:
            return ManagedTableResponse(
                connection_id = '',
                var_schema = '',
                table = '',
        )
        """

    def testManagedTableResponse(self):
        """Test ManagedTableResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
