# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.database_context_api import DatabaseContextApi


class TestDatabaseContextApi(unittest.TestCase):
    """DatabaseContextApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseContextApi()

    def tearDown(self) -> None:
        pass

    def test_delete_database_context(self) -> None:
        """Test case for delete_database_context

        Delete database context
        """
        pass

    def test_get_database_context(self) -> None:
        """Test case for get_database_context

        Get one database context
        """
        pass

    def test_list_database_contexts(self) -> None:
        """Test case for list_database_contexts

        List database contexts
        """
        pass

    def test_upsert_database_context(self) -> None:
        """Test case for upsert_database_context

        Create or update database context
        """
        pass


if __name__ == '__main__':
    unittest.main()
