# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.usage_api import UsageApi


class TestUsageApi(unittest.TestCase):
    """UsageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsageApi()

    def tearDown(self) -> None:
        pass

    def test_get_usage(self) -> None:
        """Test case for get_usage

        Get workspace usage snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
