# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.minted_upload_part_response import MintedUploadPartResponse

class TestMintedUploadPartResponse(unittest.TestCase):
    """MintedUploadPartResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MintedUploadPartResponse:
        """Test MintedUploadPartResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MintedUploadPartResponse`
        """
        model = MintedUploadPartResponse()
        if include_optional:
            return MintedUploadPartResponse(
                part_number = 56,
                url = ''
            )
        else:
            return MintedUploadPartResponse(
                part_number = 56,
                url = '',
        )
        """

    def testMintedUploadPartResponse(self):
        """Test MintedUploadPartResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
