# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for instant databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.forked_from_info import ForkedFromInfo

class TestForkedFromInfo(unittest.TestCase):
    """ForkedFromInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForkedFromInfo:
        """Test ForkedFromInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForkedFromInfo`
        """
        model = ForkedFromInfo()
        if include_optional:
            return ForkedFromInfo(
                database_id = 'dbidk9p34y6n3wd25rq4f5zr37e3p3',
                forked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                snapshot_id = 56
            )
        else:
            return ForkedFromInfo(
                database_id = 'dbidk9p34y6n3wd25rq4f5zr37e3p3',
        )
        """

    def testForkedFromInfo(self):
        """Test ForkedFromInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
