# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a workspace
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List workspaces
        """
        pass


if __name__ == '__main__':
    unittest.main()
