# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.saved_queries_api import SavedQueriesApi


class TestSavedQueriesApi(unittest.TestCase):
    """SavedQueriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SavedQueriesApi()

    def tearDown(self) -> None:
        pass

    def test_create_saved_query(self) -> None:
        """Test case for create_saved_query

        Create saved query
        """
        pass

    def test_delete_saved_query(self) -> None:
        """Test case for delete_saved_query

        Delete saved query
        """
        pass

    def test_execute_saved_query(self) -> None:
        """Test case for execute_saved_query

        Execute saved query
        """
        pass

    def test_get_saved_query(self) -> None:
        """Test case for get_saved_query

        Get saved query
        """
        pass

    def test_list_saved_queries(self) -> None:
        """Test case for list_saved_queries

        List saved queries
        """
        pass

    def test_list_saved_query_versions(self) -> None:
        """Test case for list_saved_query_versions

        List saved query versions
        """
        pass

    def test_update_saved_query(self) -> None:
        """Test case for update_saved_query

        Update saved query
        """
        pass


if __name__ == '__main__':
    unittest.main()
