# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.create_index_request import CreateIndexRequest

class TestCreateIndexRequest(unittest.TestCase):
    """CreateIndexRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIndexRequest:
        """Test CreateIndexRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIndexRequest`
        """
        model = CreateIndexRequest()
        if include_optional:
            return CreateIndexRequest(
                var_async = True,
                columns = [
                    ''
                    ],
                description = '',
                dimensions = 0,
                embedding_provider_id = '',
                index_name = '',
                index_type = '',
                metric = '',
                output_column = ''
            )
        else:
            return CreateIndexRequest(
                columns = [
                    ''
                    ],
                index_name = '',
        )
        """

    def testCreateIndexRequest(self):
        """Test CreateIndexRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
