# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.connections_api import ConnectionsApi


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectionsApi()

    def tearDown(self) -> None:
        pass

    def test_check_connection_health_handler(self) -> None:
        """Test case for check_connection_health_handler

        Check connection health
        """
        pass

    def test_create_connection_handler(self) -> None:
        """Test case for create_connection_handler

        Create connection
        """
        pass

    def test_delete_connection_handler(self) -> None:
        """Test case for delete_connection_handler

        Delete connection
        """
        pass

    def test_get_connection_handler(self) -> None:
        """Test case for get_connection_handler

        Get connection
        """
        pass

    def test_get_table_profile_handler(self) -> None:
        """Test case for get_table_profile_handler

        Get table profile
        """
        pass

    def test_list_connections_handler(self) -> None:
        """Test case for list_connections_handler

        List connections
        """
        pass

    def test_purge_connection_cache_handler(self) -> None:
        """Test case for purge_connection_cache_handler

        Purge connection cache
        """
        pass

    def test_purge_table_cache_handler(self) -> None:
        """Test case for purge_table_cache_handler

        Purge table cache
        """
        pass


if __name__ == '__main__':
    unittest.main()
