# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.uploads_api import UploadsApi


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadsApi()

    def tearDown(self) -> None:
        pass

    def test_create_upload_session_handler(self) -> None:
        """Test case for create_upload_session_handler

        Create upload session
        """
        pass

    def test_create_upload_sessions_batch_handler(self) -> None:
        """Test case for create_upload_sessions_batch_handler

        Create upload sessions in bulk
        """
        pass

    def test_finalize_upload_handler(self) -> None:
        """Test case for finalize_upload_handler

        Finalize upload
        """
        pass

    def test_list_uploads(self) -> None:
        """Test case for list_uploads

        List uploads
        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        Upload file
        """
        pass


if __name__ == '__main__':
    unittest.main()
