# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.column_profile_info import ColumnProfileInfo

class TestColumnProfileInfo(unittest.TestCase):
    """ColumnProfileInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ColumnProfileInfo:
        """Test ColumnProfileInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ColumnProfileInfo`
        """
        model = ColumnProfileInfo()
        if include_optional:
            return ColumnProfileInfo(
                cardinality = 0,
                data_type = '',
                name = '',
                null_count = 0,
                null_percentage = 1.337,
                profile = None
            )
        else:
            return ColumnProfileInfo(
                cardinality = 0,
                data_type = '',
                name = '',
                null_count = 0,
                null_percentage = 1.337,
        )
        """

    def testColumnProfileInfo(self):
        """Test ColumnProfileInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
