# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.column_profile_detail import ColumnProfileDetail

class TestColumnProfileDetail(unittest.TestCase):
    """ColumnProfileDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ColumnProfileDetail:
        """Test ColumnProfileDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ColumnProfileDetail`
        """
        model = ColumnProfileDetail()
        if include_optional:
            return ColumnProfileDetail(
                type = 'categorical',
                values = [
                    hotdata.models.category_value_info.CategoryValueInfo(
                        count = 0, 
                        value = null, )
                    ],
                avg_length = 1.337,
                max_length = 0,
                min_length = 0,
                max = '',
                mean = 1.337,
                min = '',
                false_count = 0,
                true_count = 0
            )
        else:
            return ColumnProfileDetail(
                type = 'categorical',
                values = [
                    hotdata.models.category_value_info.CategoryValueInfo(
                        count = 0, 
                        value = null, )
                    ],
                avg_length = 1.337,
                max_length = 0,
                min_length = 0,
                max = '',
                mean = 1.337,
                min = '',
                false_count = 0,
                true_count = 0,
        )
        """

    def testColumnProfileDetail(self):
        """Test ColumnProfileDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
