# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.bulk_create_databases_request import BulkCreateDatabasesRequest

class TestBulkCreateDatabasesRequest(unittest.TestCase):
    """BulkCreateDatabasesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkCreateDatabasesRequest:
        """Test BulkCreateDatabasesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkCreateDatabasesRequest`
        """
        model = BulkCreateDatabasesRequest()
        if include_optional:
            return BulkCreateDatabasesRequest(
                count = 100,
                default_catalog = 'default',
                default_schema = 'main',
                expires_at = '7d',
                idempotency_key = '3f6b1c1e-9a2b-4a5f-9a1e-2f0d6a7c8b91',
                name_template = 'tenant-{index}',
                schemas = [
                    hotdata.models.database_default_schema_decl.DatabaseDefaultSchemaDecl(
                        name = 'sales', 
                        tables = [
                            hotdata.models.database_default_table_decl.DatabaseDefaultTableDecl(
                                key = [order_id], 
                                name = 'orders', 
                                partition_by = [
                                    hotdata.models.table_partition_key.TablePartitionKey(
                                        column = 'created_at', 
                                        transform = 'day', )
                                    ], 
                                sorted_by = [
                                    hotdata.models.table_sort_key.TableSortKey(
                                        column = 'created_at', 
                                        direction = 'asc', 
                                        nulls = 'last', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return BulkCreateDatabasesRequest(
                count = 100,
        )
        """

    def testBulkCreateDatabasesRequest(self):
        """Test BulkCreateDatabasesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
