# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.finalize_upload_request import FinalizeUploadRequest

class TestFinalizeUploadRequest(unittest.TestCase):
    """FinalizeUploadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinalizeUploadRequest:
        """Test FinalizeUploadRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinalizeUploadRequest`
        """
        model = FinalizeUploadRequest()
        if include_optional:
            return FinalizeUploadRequest(
                parts = [
                    hotdata.models.finalize_upload_part.FinalizeUploadPart(
                        e_tag = '', 
                        part_number = 56, )
                    ]
            )
        else:
            return FinalizeUploadRequest(
        )
        """

    def testFinalizeUploadRequest(self):
        """Test FinalizeUploadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
