# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.load_managed_table_response import LoadManagedTableResponse

class TestLoadManagedTableResponse(unittest.TestCase):
    """LoadManagedTableResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadManagedTableResponse:
        """Test LoadManagedTableResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadManagedTableResponse`
        """
        model = LoadManagedTableResponse()
        if include_optional:
            return LoadManagedTableResponse(
                arrow_schema_json = '',
                connection_id = '',
                row_count = 0,
                schema_name = '',
                table_name = ''
            )
        else:
            return LoadManagedTableResponse(
                arrow_schema_json = '',
                connection_id = '',
                row_count = 0,
                schema_name = '',
                table_name = '',
        )
        """

    def testLoadManagedTableResponse(self):
        """Test LoadManagedTableResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
