# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.database_detail_response import DatabaseDetailResponse

class TestDatabaseDetailResponse(unittest.TestCase):
    """DatabaseDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseDetailResponse:
        """Test DatabaseDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseDetailResponse`
        """
        model = DatabaseDetailResponse()
        if include_optional:
            return DatabaseDetailResponse(
                attachments = [
                    hotdata.models.database_attachment_info.DatabaseAttachmentInfo(
                        alias = '', 
                        connection_id = '', )
                    ],
                default_catalog = '',
                default_connection_id = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                name = ''
            )
        else:
            return DatabaseDetailResponse(
                attachments = [
                    hotdata.models.database_attachment_info.DatabaseAttachmentInfo(
                        alias = '', 
                        connection_id = '', )
                    ],
                default_catalog = '',
                default_connection_id = '',
                id = '',
        )
        """

    def testDatabaseDetailResponse(self):
        """Test DatabaseDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
