# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.numeric_profile_detail import NumericProfileDetail

class TestNumericProfileDetail(unittest.TestCase):
    """NumericProfileDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NumericProfileDetail:
        """Test NumericProfileDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NumericProfileDetail`
        """
        model = NumericProfileDetail()
        if include_optional:
            return NumericProfileDetail(
                max = '',
                mean = 1.337,
                min = ''
            )
        else:
            return NumericProfileDetail(
                max = '',
                mean = 1.337,
                min = '',
        )
        """

    def testNumericProfileDetail(self):
        """Test NumericProfileDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
