# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.query_runs_api import QueryRunsApi


class TestQueryRunsApi(unittest.TestCase):
    """QueryRunsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueryRunsApi()

    def tearDown(self) -> None:
        pass

    def test_get_query_run(self) -> None:
        """Test case for get_query_run

        Get query run
        """
        pass

    def test_list_query_runs(self) -> None:
        """Test case for list_query_runs

        List query runs
        """
        pass


if __name__ == '__main__':
    unittest.main()
