# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.api.uploads_api import UploadsApi


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadsApi()

    def tearDown(self) -> None:
        pass

    def test_list_uploads(self) -> None:
        """Test case for list_uploads

        List uploads
        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        Upload file
        """
        pass


if __name__ == '__main__':
    unittest.main()
