# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hotdata.models.workspace_detail import WorkspaceDetail

class TestWorkspaceDetail(unittest.TestCase):
    """WorkspaceDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceDetail:
        """Test WorkspaceDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceDetail`
        """
        model = WorkspaceDetail()
        if include_optional:
            return WorkspaceDetail(
                public_id = 'ws_abc123',
                name = 'production-analytics',
                provision_status = 'pending',
                namespace = 'workspace-ws_abc123'
            )
        else:
            return WorkspaceDetail(
                public_id = 'ws_abc123',
                name = 'production-analytics',
                provision_status = 'pending',
                namespace = 'workspace-ws_abc123',
        )
        """

    def testWorkspaceDetail(self):
        """Test WorkspaceDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
