# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for managed databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateUploadRequest(BaseModel):
    """
    Request body for `POST /v1/uploads` and for each entry of `POST /v1/uploads/batch`.  Describes a single file you intend to upload directly to storage. The service chooses where the bytes are stored and returns a short-lived URL to `PUT` them to; you do not pick the storage location. The declared size is validated against the bytes you actually upload when you finalize.
    """ # noqa: E501
    checksum_algo: Optional[StrictStr] = Field(default=None, description="Integrity checksum algorithm you are volunteering for this file. Currently only `sha256` is accepted. Optional; pair with `checksum_value`.")
    checksum_value: Optional[StrictStr] = Field(default=None, description="Integrity checksum value, paired with `checksum_algo`. Optional.")
    content_encoding: Optional[StrictStr] = Field(default=None, description="Content encoding to record for the uploaded file (for example `gzip`). Optional.")
    content_type: Optional[StrictStr] = Field(default=None, description="Content type to record for the uploaded file (for example the Parquet, CSV, or JSON MIME type). Optional.")
    declared_size_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The exact size, in bytes, of the file you will upload. Optional. When provided, it is validated at create time against the maximum allowed size, and again at finalize against the bytes actually stored — a mismatch fails the finalize. Omit it to create a streaming (unknown-size) upload: the session is always multi-part and returns no part URLs up front; instead you mint part URLs on demand from `POST /v1/uploads/{upload_id}/parts` as you upload, and finalize validates only that the file is non-empty.")
    filename: Optional[StrictStr] = Field(default=None, description="Original file name, recorded with the upload for your own bookkeeping. Optional and advisory — it does not affect where the bytes are stored or how they are loaded.")
    part_size: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Preferred size, in bytes, of each part for a large (multi-part) upload. Optional hint — the service clamps it to the allowed part-size range and to the maximum number of parts, and ignores it for small files uploaded with a single `PUT`. Omit to let the service choose.")
    __properties: ClassVar[List[str]] = ["checksum_algo", "checksum_value", "content_encoding", "content_type", "declared_size_bytes", "filename", "part_size"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateUploadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if checksum_algo (nullable) is None
        # and model_fields_set contains the field
        if self.checksum_algo is None and "checksum_algo" in self.model_fields_set:
            _dict['checksum_algo'] = None

        # set to None if checksum_value (nullable) is None
        # and model_fields_set contains the field
        if self.checksum_value is None and "checksum_value" in self.model_fields_set:
            _dict['checksum_value'] = None

        # set to None if content_encoding (nullable) is None
        # and model_fields_set contains the field
        if self.content_encoding is None and "content_encoding" in self.model_fields_set:
            _dict['content_encoding'] = None

        # set to None if content_type (nullable) is None
        # and model_fields_set contains the field
        if self.content_type is None and "content_type" in self.model_fields_set:
            _dict['content_type'] = None

        # set to None if declared_size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.declared_size_bytes is None and "declared_size_bytes" in self.model_fields_set:
            _dict['declared_size_bytes'] = None

        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        # set to None if part_size (nullable) is None
        # and model_fields_set contains the field
        if self.part_size is None and "part_size" in self.model_fields_set:
            _dict['part_size'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateUploadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checksum_algo": obj.get("checksum_algo"),
            "checksum_value": obj.get("checksum_value"),
            "content_encoding": obj.get("content_encoding"),
            "content_type": obj.get("content_type"),
            "declared_size_bytes": obj.get("declared_size_bytes"),
            "filename": obj.get("filename"),
            "part_size": obj.get("part_size")
        })
        return _obj


