# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateIndexRequest(BaseModel):
    """
    Request body for POST .../indexes
    """ # noqa: E501
    index_name: StrictStr
    index_type: Optional[StrictStr] = Field(default=None, description="Index type: \"sorted\" (default), \"bm25\", or \"vector\"")
    metric: Optional[StrictStr] = Field(default=None, description="Distance metric for vector indexes: \"l2\" (default), \"cosine\", or \"dot\". Only relevant when index_type = \"vector\".")
    sort_columns: Optional[List[StrictStr]] = None
    text_columns: Optional[List[StrictStr]] = Field(default=None, description="Text columns for BM25 indexes")
    vector_columns: Optional[List[StrictStr]] = Field(default=None, description="Vector column for vector indexes (exactly one entry required)")
    __properties: ClassVar[List[str]] = ["index_name", "index_type", "metric", "sort_columns", "text_columns", "vector_columns"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateIndexRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sort_columns (nullable) is None
        # and model_fields_set contains the field
        if self.sort_columns is None and "sort_columns" in self.model_fields_set:
            _dict['sort_columns'] = None

        # set to None if text_columns (nullable) is None
        # and model_fields_set contains the field
        if self.text_columns is None and "text_columns" in self.model_fields_set:
            _dict['text_columns'] = None

        # set to None if vector_columns (nullable) is None
        # and model_fields_set contains the field
        if self.vector_columns is None and "vector_columns" in self.model_fields_set:
            _dict['vector_columns'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateIndexRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index_name": obj.get("index_name"),
            "index_type": obj.get("index_type"),
            "metric": obj.get("metric"),
            "sort_columns": obj.get("sort_columns"),
            "text_columns": obj.get("text_columns"),
            "vector_columns": obj.get("vector_columns")
        })
        return _obj


