# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateEmbeddingProviderRequest(BaseModel):
    """
    Request body for POST /embedding-providers
    """ # noqa: E501
    api_key: Optional[StrictStr] = Field(default=None, description="Inline API key. If provided, a secret is auto-created and referenced. Cannot be used together with `secret_name`.")
    config: Optional[Any] = None
    name: StrictStr
    provider_type: StrictStr = Field(description="Provider type: \"local\" or \"service\"")
    secret_name: Optional[StrictStr] = Field(default=None, description="Reference an existing secret by name (for service providers).")
    __properties: ClassVar[List[str]] = ["api_key", "config", "name", "provider_type", "secret_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateEmbeddingProviderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if api_key (nullable) is None
        # and model_fields_set contains the field
        if self.api_key is None and "api_key" in self.model_fields_set:
            _dict['api_key'] = None

        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if secret_name (nullable) is None
        # and model_fields_set contains the field
        if self.secret_name is None and "secret_name" in self.model_fields_set:
            _dict['secret_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateEmbeddingProviderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key": obj.get("api_key"),
            "config": obj.get("config"),
            "name": obj.get("name"),
            "provider_type": obj.get("provider_type"),
            "secret_name": obj.get("secret_name")
        })
        return _obj


