# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DiscoveryStatus(str, Enum):
    """
    Discovery status for connection creation
    """

    """
    allowed enum values
    """
    SUCCESS = 'success'
    SKIPPED = 'skipped'
    FAILED = 'failed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DiscoveryStatus from a JSON string"""
        return cls(json.loads(json_str))


