# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for instant databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ForkedFromInfo(BaseModel):
    """
    Where a forked database came from, and which state of the source it copied.  Present only on a database that was created by forking another one. It is a record of how this database came to exist, not a live link: the fork and its source are independent from the moment the fork is created, and either can change or be deleted without affecting the other.  Forks created before lineage was recorded carry no `forked_from`.
    """ # noqa: E501
    database_id: StrictStr = Field(description="ID of the database that was forked. The database may since have been deleted — the record outlives it — so this is not guaranteed to resolve.")
    description: Optional[StrictStr] = Field(default=None, description="Why the fork was taken, as given when it was created. Absent when none was given.")
    forked_at: Optional[datetime] = Field(default=None, description="When the fork was taken.")
    name: Optional[StrictStr] = Field(default=None, description="Display label the source carried when the fork was taken, kept so a deleted source still reads as more than an ID.")
    snapshot_id: Optional[StrictInt] = Field(default=None, description="Marks the version of the source that this fork copied — its table set and their contents as of that moment. It is a point in time rather than a per-database revision count, so two forks of a source that did not change still report different values, and the numbers are not a way to tell whether a source has changed. Absent only on forks taken before the version was recorded.")
    __properties: ClassVar[List[str]] = ["database_id", "description", "forked_at", "name", "snapshot_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForkedFromInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if forked_at (nullable) is None
        # and model_fields_set contains the field
        if self.forked_at is None and "forked_at" in self.model_fields_set:
            _dict['forked_at'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if snapshot_id (nullable) is None
        # and model_fields_set contains the field
        if self.snapshot_id is None and "snapshot_id" in self.model_fields_set:
            _dict['snapshot_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForkedFromInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "database_id": obj.get("database_id"),
            "description": obj.get("description"),
            "forked_at": obj.get("forked_at"),
            "name": obj.get("name"),
            "snapshot_id": obj.get("snapshot_id")
        })
        return _obj


