# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JobType(str, Enum):
    """
    Background job types returned by the API.
    """

    """
    allowed enum values
    """
    NOOP = 'noop'
    DATA_REFRESH_TABLE = 'data_refresh_table'
    DATA_REFRESH_CONNECTION = 'data_refresh_connection'
    DATASET_REFRESH = 'dataset_refresh'
    CREATE_INDEX = 'create_index'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobType from a JSON string"""
        return cls(json.loads(json_str))


