# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for instant databases, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LineageAncestorInfo(BaseModel):
    """
    One database up a fork chain.
    """ # noqa: E501
    database_id: StrictStr
    description: Optional[StrictStr] = Field(default=None, description="Why the next database down the chain was forked from it, as given at the time. Absent when none was given.")
    exists: StrictBool = Field(description="False once the ancestor has been deleted. Its place in the chain is kept either way, and the ancestry continues past it.")
    forked_at: Optional[datetime] = Field(default=None, description="When the next database down the chain was forked from it.")
    name: Optional[StrictStr] = Field(default=None, description="The ancestor's current label, or the one captured at fork time when it no longer exists.")
    snapshot_id: Optional[StrictInt] = Field(default=None, description="Version of this ancestor's data that the next database down the chain copied. See `forked_from.snapshot_id`.")
    __properties: ClassVar[List[str]] = ["database_id", "description", "exists", "forked_at", "name", "snapshot_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LineageAncestorInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if forked_at (nullable) is None
        # and model_fields_set contains the field
        if self.forked_at is None and "forked_at" in self.model_fields_set:
            _dict['forked_at'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if snapshot_id (nullable) is None
        # and model_fields_set contains the field
        if self.snapshot_id is None and "snapshot_id" in self.model_fields_set:
            _dict['snapshot_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LineageAncestorInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "database_id": obj.get("database_id"),
            "description": obj.get("description"),
            "exists": obj.get("exists"),
            "forked_at": obj.get("forked_at"),
            "name": obj.get("name"),
            "snapshot_id": obj.get("snapshot_id")
        })
        return _obj


