# coding: utf-8

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class QueryRunInfo(BaseModel):
    """
    Single query run for listing
    """ # noqa: E501
    completed_at: Optional[datetime] = None
    created_at: datetime
    error_message: Optional[StrictStr] = None
    execution_time_ms: Optional[StrictInt] = None
    id: StrictStr
    result_id: Optional[StrictStr] = None
    row_count: Optional[StrictInt] = None
    saved_query_id: Optional[StrictStr] = None
    saved_query_version: Optional[StrictInt] = None
    snapshot_id: StrictStr
    sql_hash: StrictStr
    sql_text: StrictStr
    status: StrictStr
    trace_id: Optional[StrictStr] = None
    warning_message: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["completed_at", "created_at", "error_message", "execution_time_ms", "id", "result_id", "row_count", "saved_query_id", "saved_query_version", "snapshot_id", "sql_hash", "sql_text", "status", "trace_id", "warning_message"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryRunInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if execution_time_ms (nullable) is None
        # and model_fields_set contains the field
        if self.execution_time_ms is None and "execution_time_ms" in self.model_fields_set:
            _dict['execution_time_ms'] = None

        # set to None if result_id (nullable) is None
        # and model_fields_set contains the field
        if self.result_id is None and "result_id" in self.model_fields_set:
            _dict['result_id'] = None

        # set to None if row_count (nullable) is None
        # and model_fields_set contains the field
        if self.row_count is None and "row_count" in self.model_fields_set:
            _dict['row_count'] = None

        # set to None if saved_query_id (nullable) is None
        # and model_fields_set contains the field
        if self.saved_query_id is None and "saved_query_id" in self.model_fields_set:
            _dict['saved_query_id'] = None

        # set to None if saved_query_version (nullable) is None
        # and model_fields_set contains the field
        if self.saved_query_version is None and "saved_query_version" in self.model_fields_set:
            _dict['saved_query_version'] = None

        # set to None if trace_id (nullable) is None
        # and model_fields_set contains the field
        if self.trace_id is None and "trace_id" in self.model_fields_set:
            _dict['trace_id'] = None

        # set to None if warning_message (nullable) is None
        # and model_fields_set contains the field
        if self.warning_message is None and "warning_message" in self.model_fields_set:
            _dict['warning_message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryRunInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "error_message": obj.get("error_message"),
            "execution_time_ms": obj.get("execution_time_ms"),
            "id": obj.get("id"),
            "result_id": obj.get("result_id"),
            "row_count": obj.get("row_count"),
            "saved_query_id": obj.get("saved_query_id"),
            "saved_query_version": obj.get("saved_query_version"),
            "snapshot_id": obj.get("snapshot_id"),
            "sql_hash": obj.get("sql_hash"),
            "sql_text": obj.get("sql_text"),
            "status": obj.get("status"),
            "trace_id": obj.get("trace_id"),
            "warning_message": obj.get("warning_message")
        })
        return _obj


