# coding: utf-8

"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from hotdata.models.column_profile_info import ColumnProfileInfo
from typing import Optional, Set
from typing_extensions import Self

class TableProfileResponse(BaseModel):
    """
    Column-level statistics for a synced table. Profiles are computed at sync time and include per-column cardinality, null counts, and type-specific details.
    """ # noqa: E501
    columns: List[ColumnProfileInfo] = Field(description="Per-column profile statistics")
    connection: StrictStr = Field(description="Connection name")
    row_count: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total number of rows in the table")
    var_schema: StrictStr = Field(description="Schema name", alias="schema")
    synced_at: Optional[Any] = Field(default=None, description="When the table was last synced")
    table: StrictStr = Field(description="Table name")
    __properties: ClassVar[List[str]] = ["columns", "connection", "row_count", "schema", "synced_at", "table"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableProfileResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in columns (list)
        _items = []
        if self.columns:
            for _item_columns in self.columns:
                if _item_columns:
                    _items.append(_item_columns.to_dict())
            _dict['columns'] = _items
        # set to None if synced_at (nullable) is None
        # and model_fields_set contains the field
        if self.synced_at is None and "synced_at" in self.model_fields_set:
            _dict['synced_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableProfileResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "columns": [ColumnProfileInfo.from_dict(_item) for _item in obj["columns"]] if obj.get("columns") is not None else None,
            "connection": obj.get("connection"),
            "row_count": obj.get("row_count"),
            "schema": obj.get("schema"),
            "synced_at": obj.get("synced_at"),
            "table": obj.get("table")
        })
        return _obj


