"""
    HotData API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr
from typing import Optional
from typing_extensions import Annotated
from hotdata.models.information_schema_response import InformationSchemaResponse

from hotdata.api_client import ApiClient, RequestSerialized
from hotdata.api_response import ApiResponse
from hotdata.rest import RESTResponseType


class InformationSchemaApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def information_schema(
        self,
        connection_id: Annotated[Optional[StrictStr], Field(description="Filter by connection ID")] = None,
        var_schema: Annotated[Optional[StrictStr], Field(description="Filter by schema name (supports % wildcards)")] = None,
        table: Annotated[Optional[StrictStr], Field(description="Filter by table name (supports % wildcards)")] = None,
        include_columns: Annotated[Optional[StrictBool], Field(description="Include column definitions (default: false)")] = None,
        limit: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Maximum number of tables per page")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Pagination cursor from a previous response")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> InformationSchemaResponse:
        """List tables

        List discovered tables with optional filtering and pagination. Supports wildcard patterns (SQL %) for schema and table name filters. Set include_columns=true to include column definitions (omitted by default).

        :param connection_id: Filter by connection ID
        :type connection_id: str
        :param var_schema: Filter by schema name (supports % wildcards)
        :type var_schema: str
        :param table: Filter by table name (supports % wildcards)
        :type table: str
        :param include_columns: Include column definitions (default: false)
        :type include_columns: bool
        :param limit: Maximum number of tables per page
        :type limit: int
        :param cursor: Pagination cursor from a previous response
        :type cursor: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._information_schema_serialize(
            connection_id=connection_id,
            var_schema=var_schema,
            table=table,
            include_columns=include_columns,
            limit=limit,
            cursor=cursor,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InformationSchemaResponse",
            '404': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def information_schema_with_http_info(
        self,
        connection_id: Annotated[Optional[StrictStr], Field(description="Filter by connection ID")] = None,
        var_schema: Annotated[Optional[StrictStr], Field(description="Filter by schema name (supports % wildcards)")] = None,
        table: Annotated[Optional[StrictStr], Field(description="Filter by table name (supports % wildcards)")] = None,
        include_columns: Annotated[Optional[StrictBool], Field(description="Include column definitions (default: false)")] = None,
        limit: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Maximum number of tables per page")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Pagination cursor from a previous response")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[InformationSchemaResponse]:
        """List tables

        List discovered tables with optional filtering and pagination. Supports wildcard patterns (SQL %) for schema and table name filters. Set include_columns=true to include column definitions (omitted by default).

        :param connection_id: Filter by connection ID
        :type connection_id: str
        :param var_schema: Filter by schema name (supports % wildcards)
        :type var_schema: str
        :param table: Filter by table name (supports % wildcards)
        :type table: str
        :param include_columns: Include column definitions (default: false)
        :type include_columns: bool
        :param limit: Maximum number of tables per page
        :type limit: int
        :param cursor: Pagination cursor from a previous response
        :type cursor: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._information_schema_serialize(
            connection_id=connection_id,
            var_schema=var_schema,
            table=table,
            include_columns=include_columns,
            limit=limit,
            cursor=cursor,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InformationSchemaResponse",
            '404': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def information_schema_without_preload_content(
        self,
        connection_id: Annotated[Optional[StrictStr], Field(description="Filter by connection ID")] = None,
        var_schema: Annotated[Optional[StrictStr], Field(description="Filter by schema name (supports % wildcards)")] = None,
        table: Annotated[Optional[StrictStr], Field(description="Filter by table name (supports % wildcards)")] = None,
        include_columns: Annotated[Optional[StrictBool], Field(description="Include column definitions (default: false)")] = None,
        limit: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Maximum number of tables per page")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Pagination cursor from a previous response")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List tables

        List discovered tables with optional filtering and pagination. Supports wildcard patterns (SQL %) for schema and table name filters. Set include_columns=true to include column definitions (omitted by default).

        :param connection_id: Filter by connection ID
        :type connection_id: str
        :param var_schema: Filter by schema name (supports % wildcards)
        :type var_schema: str
        :param table: Filter by table name (supports % wildcards)
        :type table: str
        :param include_columns: Include column definitions (default: false)
        :type include_columns: bool
        :param limit: Maximum number of tables per page
        :type limit: int
        :param cursor: Pagination cursor from a previous response
        :type cursor: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._information_schema_serialize(
            connection_id=connection_id,
            var_schema=var_schema,
            table=table,
            include_columns=include_columns,
            limit=limit,
            cursor=cursor,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "InformationSchemaResponse",
            '404': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _information_schema_serialize(
        self,
        connection_id,
        var_schema,
        table,
        include_columns,
        limit,
        cursor,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if connection_id is not None:
            
            _query_params.append(('connection_id', connection_id))
            
        if var_schema is not None:
            
            _query_params.append(('schema', var_schema))
            
        if table is not None:
            
            _query_params.append(('table', table))
            
        if include_columns is not None:
            
            _query_params.append(('include_columns', include_columns))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/information_schema',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


