# coding: utf-8

# flake8: noqa

"""
    Hotdata API

    Powerful data platform API for datasets, queries, and analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: developers@hotdata.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ConnectionTypesApi",
    "ConnectionsApi",
    "DatasetsApi",
    "IndexesApi",
    "InformationSchemaApi",
    "QueryApi",
    "QueryRunsApi",
    "RefreshApi",
    "ResultsApi",
    "SavedQueriesApi",
    "SecretsApi",
    "UploadsApi",
    "WorkspacesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiErrorDetail",
    "ApiErrorResponse",
    "BooleanProfileDetail",
    "CategoricalProfileDetail",
    "CategoryValueInfo",
    "ColumnInfo",
    "ColumnProfileDetail",
    "ColumnProfileDetailOneOf",
    "ColumnProfileDetailOneOf1",
    "ColumnProfileDetailOneOf2",
    "ColumnProfileDetailOneOf3",
    "ColumnProfileDetailOneOf4",
    "ColumnProfileInfo",
    "ColumnTypeSpec",
    "ConnectionHealthResponse",
    "ConnectionInfo",
    "ConnectionRefreshResult",
    "ConnectionSchemaError",
    "ConnectionTypeDetail",
    "ConnectionTypeSummary",
    "CreateConnectionRequest",
    "CreateConnectionResponse",
    "CreateDatasetRequest",
    "CreateDatasetResponse",
    "CreateIndexRequest",
    "CreateSavedQueryRequest",
    "CreateSecretRequest",
    "CreateSecretResponse",
    "CreateWorkspaceRequest",
    "CreateWorkspaceResponse",
    "DatasetSource",
    "DatasetSummary",
    "DatasetVersionSummary",
    "DiscoveryStatus",
    "Error",
    "ExecuteSavedQueryRequest",
    "GetConnectionResponse",
    "GetDatasetResponse",
    "GetResultResponse",
    "GetSecretResponse",
    "IndexInfoResponse",
    "IndexStatus",
    "InformationSchemaResponse",
    "InlineData",
    "InlineDatasetSource",
    "ListConnectionTypesResponse",
    "ListConnectionsResponse",
    "ListDatasetVersionsResponse",
    "ListDatasetsResponse",
    "ListIndexesResponse",
    "ListQueryRunsResponse",
    "ListResultsResponse",
    "ListSavedQueriesResponse",
    "ListSavedQueryVersionsResponse",
    "ListSecretsResponse",
    "ListUploadsResponse",
    "ListWorkspacesResponse",
    "NumericProfileDetail",
    "QueryRequest",
    "QueryResponse",
    "QueryRunInfo",
    "RefreshDatasetResponse",
    "RefreshRequest",
    "RefreshResponse",
    "RefreshWarning",
    "ResultInfo",
    "SavedQueryDatasetSource",
    "SavedQueryDetail",
    "SavedQuerySummary",
    "SavedQueryVersionInfo",
    "SchemaRefreshResult",
    "SecretMetadataResponse",
    "TableInfo",
    "TableProfileResponse",
    "TableRefreshError",
    "TableRefreshResult",
    "TemporalProfileDetail",
    "TextProfileDetail",
    "UpdateDatasetRequest",
    "UpdateDatasetResponse",
    "UpdateSavedQueryRequest",
    "UpdateSecretRequest",
    "UpdateSecretResponse",
    "UploadDatasetSource",
    "UploadInfo",
    "UploadResponse",
    "UrlDatasetSource",
    "WorkspaceDetail",
    "WorkspaceListItem",
]

# import apis into sdk package
from hotdata.api.connection_types_api import ConnectionTypesApi as ConnectionTypesApi
from hotdata.api.connections_api import ConnectionsApi as ConnectionsApi
from hotdata.api.datasets_api import DatasetsApi as DatasetsApi
from hotdata.api.indexes_api import IndexesApi as IndexesApi
from hotdata.api.information_schema_api import InformationSchemaApi as InformationSchemaApi
from hotdata.api.query_api import QueryApi as QueryApi
from hotdata.api.query_runs_api import QueryRunsApi as QueryRunsApi
from hotdata.api.refresh_api import RefreshApi as RefreshApi
from hotdata.api.results_api import ResultsApi as ResultsApi
from hotdata.api.saved_queries_api import SavedQueriesApi as SavedQueriesApi
from hotdata.api.secrets_api import SecretsApi as SecretsApi
from hotdata.api.uploads_api import UploadsApi as UploadsApi
from hotdata.api.workspaces_api import WorkspacesApi as WorkspacesApi

# import ApiClient
from hotdata.api_response import ApiResponse as ApiResponse
from hotdata.api_client import ApiClient as ApiClient
from hotdata.configuration import Configuration as Configuration
from hotdata.exceptions import OpenApiException as OpenApiException
from hotdata.exceptions import ApiTypeError as ApiTypeError
from hotdata.exceptions import ApiValueError as ApiValueError
from hotdata.exceptions import ApiKeyError as ApiKeyError
from hotdata.exceptions import ApiAttributeError as ApiAttributeError
from hotdata.exceptions import ApiException as ApiException

# import models into sdk package
from hotdata.models.api_error_detail import ApiErrorDetail as ApiErrorDetail
from hotdata.models.api_error_response import ApiErrorResponse as ApiErrorResponse
from hotdata.models.boolean_profile_detail import BooleanProfileDetail as BooleanProfileDetail
from hotdata.models.categorical_profile_detail import CategoricalProfileDetail as CategoricalProfileDetail
from hotdata.models.category_value_info import CategoryValueInfo as CategoryValueInfo
from hotdata.models.column_info import ColumnInfo as ColumnInfo
from hotdata.models.column_profile_detail import ColumnProfileDetail as ColumnProfileDetail
from hotdata.models.column_profile_detail_one_of import ColumnProfileDetailOneOf as ColumnProfileDetailOneOf
from hotdata.models.column_profile_detail_one_of1 import ColumnProfileDetailOneOf1 as ColumnProfileDetailOneOf1
from hotdata.models.column_profile_detail_one_of2 import ColumnProfileDetailOneOf2 as ColumnProfileDetailOneOf2
from hotdata.models.column_profile_detail_one_of3 import ColumnProfileDetailOneOf3 as ColumnProfileDetailOneOf3
from hotdata.models.column_profile_detail_one_of4 import ColumnProfileDetailOneOf4 as ColumnProfileDetailOneOf4
from hotdata.models.column_profile_info import ColumnProfileInfo as ColumnProfileInfo
from hotdata.models.column_type_spec import ColumnTypeSpec as ColumnTypeSpec
from hotdata.models.connection_health_response import ConnectionHealthResponse as ConnectionHealthResponse
from hotdata.models.connection_info import ConnectionInfo as ConnectionInfo
from hotdata.models.connection_refresh_result import ConnectionRefreshResult as ConnectionRefreshResult
from hotdata.models.connection_schema_error import ConnectionSchemaError as ConnectionSchemaError
from hotdata.models.connection_type_detail import ConnectionTypeDetail as ConnectionTypeDetail
from hotdata.models.connection_type_summary import ConnectionTypeSummary as ConnectionTypeSummary
from hotdata.models.create_connection_request import CreateConnectionRequest as CreateConnectionRequest
from hotdata.models.create_connection_response import CreateConnectionResponse as CreateConnectionResponse
from hotdata.models.create_dataset_request import CreateDatasetRequest as CreateDatasetRequest
from hotdata.models.create_dataset_response import CreateDatasetResponse as CreateDatasetResponse
from hotdata.models.create_index_request import CreateIndexRequest as CreateIndexRequest
from hotdata.models.create_saved_query_request import CreateSavedQueryRequest as CreateSavedQueryRequest
from hotdata.models.create_secret_request import CreateSecretRequest as CreateSecretRequest
from hotdata.models.create_secret_response import CreateSecretResponse as CreateSecretResponse
from hotdata.models.create_workspace_request import CreateWorkspaceRequest as CreateWorkspaceRequest
from hotdata.models.create_workspace_response import CreateWorkspaceResponse as CreateWorkspaceResponse
from hotdata.models.dataset_source import DatasetSource as DatasetSource
from hotdata.models.dataset_summary import DatasetSummary as DatasetSummary
from hotdata.models.dataset_version_summary import DatasetVersionSummary as DatasetVersionSummary
from hotdata.models.discovery_status import DiscoveryStatus as DiscoveryStatus
from hotdata.models.error import Error as Error
from hotdata.models.execute_saved_query_request import ExecuteSavedQueryRequest as ExecuteSavedQueryRequest
from hotdata.models.get_connection_response import GetConnectionResponse as GetConnectionResponse
from hotdata.models.get_dataset_response import GetDatasetResponse as GetDatasetResponse
from hotdata.models.get_result_response import GetResultResponse as GetResultResponse
from hotdata.models.get_secret_response import GetSecretResponse as GetSecretResponse
from hotdata.models.index_info_response import IndexInfoResponse as IndexInfoResponse
from hotdata.models.index_status import IndexStatus as IndexStatus
from hotdata.models.information_schema_response import InformationSchemaResponse as InformationSchemaResponse
from hotdata.models.inline_data import InlineData as InlineData
from hotdata.models.inline_dataset_source import InlineDatasetSource as InlineDatasetSource
from hotdata.models.list_connection_types_response import ListConnectionTypesResponse as ListConnectionTypesResponse
from hotdata.models.list_connections_response import ListConnectionsResponse as ListConnectionsResponse
from hotdata.models.list_dataset_versions_response import ListDatasetVersionsResponse as ListDatasetVersionsResponse
from hotdata.models.list_datasets_response import ListDatasetsResponse as ListDatasetsResponse
from hotdata.models.list_indexes_response import ListIndexesResponse as ListIndexesResponse
from hotdata.models.list_query_runs_response import ListQueryRunsResponse as ListQueryRunsResponse
from hotdata.models.list_results_response import ListResultsResponse as ListResultsResponse
from hotdata.models.list_saved_queries_response import ListSavedQueriesResponse as ListSavedQueriesResponse
from hotdata.models.list_saved_query_versions_response import ListSavedQueryVersionsResponse as ListSavedQueryVersionsResponse
from hotdata.models.list_secrets_response import ListSecretsResponse as ListSecretsResponse
from hotdata.models.list_uploads_response import ListUploadsResponse as ListUploadsResponse
from hotdata.models.list_workspaces_response import ListWorkspacesResponse as ListWorkspacesResponse
from hotdata.models.numeric_profile_detail import NumericProfileDetail as NumericProfileDetail
from hotdata.models.query_request import QueryRequest as QueryRequest
from hotdata.models.query_response import QueryResponse as QueryResponse
from hotdata.models.query_run_info import QueryRunInfo as QueryRunInfo
from hotdata.models.refresh_dataset_response import RefreshDatasetResponse as RefreshDatasetResponse
from hotdata.models.refresh_request import RefreshRequest as RefreshRequest
from hotdata.models.refresh_response import RefreshResponse as RefreshResponse
from hotdata.models.refresh_warning import RefreshWarning as RefreshWarning
from hotdata.models.result_info import ResultInfo as ResultInfo
from hotdata.models.saved_query_dataset_source import SavedQueryDatasetSource as SavedQueryDatasetSource
from hotdata.models.saved_query_detail import SavedQueryDetail as SavedQueryDetail
from hotdata.models.saved_query_summary import SavedQuerySummary as SavedQuerySummary
from hotdata.models.saved_query_version_info import SavedQueryVersionInfo as SavedQueryVersionInfo
from hotdata.models.schema_refresh_result import SchemaRefreshResult as SchemaRefreshResult
from hotdata.models.secret_metadata_response import SecretMetadataResponse as SecretMetadataResponse
from hotdata.models.table_info import TableInfo as TableInfo
from hotdata.models.table_profile_response import TableProfileResponse as TableProfileResponse
from hotdata.models.table_refresh_error import TableRefreshError as TableRefreshError
from hotdata.models.table_refresh_result import TableRefreshResult as TableRefreshResult
from hotdata.models.temporal_profile_detail import TemporalProfileDetail as TemporalProfileDetail
from hotdata.models.text_profile_detail import TextProfileDetail as TextProfileDetail
from hotdata.models.update_dataset_request import UpdateDatasetRequest as UpdateDatasetRequest
from hotdata.models.update_dataset_response import UpdateDatasetResponse as UpdateDatasetResponse
from hotdata.models.update_saved_query_request import UpdateSavedQueryRequest as UpdateSavedQueryRequest
from hotdata.models.update_secret_request import UpdateSecretRequest as UpdateSecretRequest
from hotdata.models.update_secret_response import UpdateSecretResponse as UpdateSecretResponse
from hotdata.models.upload_dataset_source import UploadDatasetSource as UploadDatasetSource
from hotdata.models.upload_info import UploadInfo as UploadInfo
from hotdata.models.upload_response import UploadResponse as UploadResponse
from hotdata.models.url_dataset_source import UrlDatasetSource as UrlDatasetSource
from hotdata.models.workspace_detail import WorkspaceDetail as WorkspaceDetail
from hotdata.models.workspace_list_item import WorkspaceListItem as WorkspaceListItem

